Improved API fetching and XML designs, updated data display.
dilaefendioglu/Dog-Discovery pull request #1
Opened 2024-08-20 20:32 UTC by dilaefendioglu

2024-08-22 15:25 UTC, kerimisoffline requested changes
Eline sağlık.

2024-08-22 15:25 UTC, kerimisoffline commented on app/src/main/java/com/dilaefendioglu/dogdiscovery/api/DogFreeApi.kt
> +            .baseUrl("https://freetestapi.com/api/v1/")
Url'leri Constant sınıfı içerisine alabiliriz.

2024-08-22 15:25 UTC, kerimisoffline commented on app/src/main/java/com/dilaefendioglu/dogdiscovery/api/DogImageApi.kt
> +            .baseUrl("https://dog.ceo/api/")
Url'leri Constant sınıfı içerisine alabiliriz.

2024-08-22 15:25 UTC, kerimisoffline commented on app/src/main/java/com/dilaefendioglu/dogdiscovery/service/DogApiService.kt
> +    }
Tüm dosyalarda reformat yapalım. Control+Alt+L

2024-08-22 15:25 UTC, kerimisoffline commented on app/src/main/java/com/dilaefendioglu/dogdiscovery/data/DogFreeResponse.kt
> +    val breed_group: String,
```suggestion
        @SerializedName("breed_group") val group: String,
```
underscore yerine camelCase kullanalım.

2024-08-22 15:25 UTC, kerimisoffline commented on app/src/main/res/layout/fragment_list.xml
> +<FrameLayout xmlns:android="http://schemas.android.com/apk/res/android"
En dışta LinearLayout, Constraintlayout yada relative layout kullanabiliriz.

2024-08-22 15:25 UTC, kerimisoffline commented on app/src/main/java/com/dilaefendioglu/dogdiscovery/fragment/ListFragment.kt
> +                putSerializable("breed", dog)
hardcoded text "breed" Constant sınıfından alalım.

2024-08-22 15:25 UTC, kerimisoffline commented on app/src/main/java/com/dilaefendioglu/dogdiscovery/MainViewModel.kt
> +    val hasError: LiveData<Boolean> get() = _hasError
Ui'da hataları dinleyip, dialog yada mesaj çıkartabiliriz.

2024-08-22 15:25 UTC, kerimisoffline commented on app/src/main/java/com/dilaefendioglu/dogdiscovery/MainViewModel.kt
> +    private val DogImageService = DogImageApi.api
```suggestion
    private val dogImageService : DogImageService = DogImageApi.api
```

2024-08-22 15:25 UTC, kerimisoffline commented on app/src/main/java/com/dilaefendioglu/dogdiscovery/MainActivity.kt
> +        return navController.navigateUp() || super.onSupportNavigateUp()
Kaldırabiliriz, navigation component kullandık. activity_main'de bağlama işlemini yaptık.

2024-08-22 15:25 UTC, kerimisoffline commented on app/src/main/res/layout/item_dog.xml
> +    app:cardCornerRadius="8dp"
dimens.xml'den okuyalım.

2024-08-22 15:25 UTC, kerimisoffline commented on app/src/main/res/layout/item_dog.xml
> +            android:padding="6dp">
dimens.xml'den okuyalım.

2024-08-22 15:25 UTC, kerimisoffline commented on app/src/main/java/com/dilaefendioglu/dogdiscovery/fragment/DetailFragment.kt
> +        val dog = arguments?.getSerializable("breed") as? DogFreeResponse
SafeArgs kullanabiliriz. for ex;
val dog = DogDetailsFragmentArgs.fromBundle(requireArguments()).breed

2024-08-22 15:25 UTC, kerimisoffline commented on app/src/main/java/com/dilaefendioglu/dogdiscovery/fragment/DetailFragment.kt
> +            binding.txtBreedGroup.text = StringBuilder().append("Breed Group: ").append(dog.breed_group)
"Breed Group: " string.xml'den çekelim.

2024-08-22 15:25 UTC, kerimisoffline commented on app/src/main/java/com/dilaefendioglu/dogdiscovery/fragment/DetailFragment.kt
> +            Picasso.get()
Extention fonksiyon olarak yazalım.

2024-08-23 06:38 UTC, TamerSarioglu requested changes

2024-08-23 06:38 UTC, TamerSarioglu commented on app/src/main/java/com/dilaefendioglu/dogdiscovery/SplashScreen.kt
> +class SplashScreen : AppCompatActivity() {
Bu classı kaldıralım. Uygulamada şu anda 2 adet Splash screen gözüküyor API 33 ve üstünde. Eğer splash icon değiştirmek istiyorsan Splash Screen API araştırabilirsin.

2024-08-23 06:38 UTC, TamerSarioglu commented on app/src/main/java/com/dilaefendioglu/dogdiscovery/MainViewModelFactory.kt
> +class MainViewModelFactory(
Bu Factory classa muhtemelen viewModel çağırılırken bir argüman pasladığın için yazdın ancak buna gerek yok. Kaldırabiliriz.

2024-08-23 06:38 UTC, TamerSarioglu commented on app/src/main/java/com/dilaefendioglu/dogdiscovery/MainViewModel.kt
> +    private val breedsService: DogApiService
MainView Model Factory classını sildikten sonra muhtemelen hata alacaksın. Bu viewModeli şu şekilde güncelleyebilirsin -> 
`class MainViewModel : ViewModel() {

    private val breedsService = DogFreeApi.api` diyerek argümanı içerde instance olarak çağırabilirsin.

2024-08-23 06:38 UTC, TamerSarioglu commented on app/src/main/java/com/dilaefendioglu/dogdiscovery/fragment/DetailFragment.kt
> +            binding.imgBreed.setImageUrl(dog.images)
Burada şöyle bir ext fun yazılabilir 
`private fun TextView.setTextWithLabel(labelResId: Int, value: String?) {
    text = context.getString(labelResId).plus(value.orEmpty())
}`

sonrasında örnek olarak -> `txtBreedGroup.setTextWithLabel(R.string.breed_group, dog.breedgroup)`

2024-08-23 06:38 UTC, TamerSarioglu commented on app/src/main/java/com/dilaefendioglu/dogdiscovery/service/DogApiService.kt
> +
fazla boşluk var.

2024-08-23 06:38 UTC, TamerSarioglu commented on app/src/main/java/com/dilaefendioglu/dogdiscovery/utils/Constants.kt
> +    const val FREETEST_APİ_BASE = "https://freetestapi.com/api/v1/"
Türkçe büyük noktalı karakterler kullanmamalıyız.

2024-08-23 07:23 UTC, TamerSarioglu approved these changes
Eline sağlık 👍

2024-08-23 09:13 UTC, kerimisoffline approved these changes
Eline sağlık.

2024-08-23 10:12 UTC, merged